[project]
name = "energy-platform"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.34.2",
    "tenacity>=9.1.4",
    "tzdata>=2026.4",
]

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyspark>=4.2.0",
    "pytest>=9.1.1",
]

[project.scripts]
hello-job = "energy_platform.entrypoints:hello_job"
